/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppBusinessRouteImport } from './routes/_app/business'
import { Route as AppEinvoiceRouteImport } from './routes/_app/einvoice'
import { Route as AppReconciliationRouteImport } from './routes/_app/reconciliation'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppInvoicesIndexRouteImport } from './routes/_app/invoices/index'
import { Route as AppInvoicesIdRouteImport } from './routes/_app/invoices/$id'
import { Route as AppInvoicesNewRouteImport } from './routes/_app/invoices/new'
import { Route as AppMastersCustomersRouteImport } from './routes/_app/masters/customers'
import { Route as AppMastersProductsRouteImport } from './routes/_app/masters/products'
import { Route as AppReturnsGstr1RouteImport } from './routes/_app/returns/gstr-1'
import { Route as AppReturnsGstr3bRouteImport } from './routes/_app/returns/gstr-3b'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBusinessRoute = AppBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AppRoute,
} as any)
const AppEinvoiceRoute = AppEinvoiceRouteImport.update({
  id: '/einvoice',
  path: '/einvoice',
  getParentRoute: () => AppRoute,
} as any)
const AppReconciliationRoute = AppReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIdRoute = AppInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesNewRoute = AppInvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => AppRoute,
} as any)
const AppMastersCustomersRoute = AppMastersCustomersRouteImport.update({
  id: '/masters/customers',
  path: '/masters/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppMastersProductsRoute = AppMastersProductsRouteImport.update({
  id: '/masters/products',
  path: '/masters/products',
  getParentRoute: () => AppRoute,
} as any)
const AppReturnsGstr1Route = AppReturnsGstr1RouteImport.update({
  id: '/returns/gstr-1',
  path: '/returns/gstr-1',
  getParentRoute: () => AppRoute,
} as any)
const AppReturnsGstr3bRoute = AppReturnsGstr3bRouteImport.update({
  id: '/returns/gstr-3b',
  path: '/returns/gstr-3b',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/business': typeof AppBusinessRoute
  '/einvoice': typeof AppEinvoiceRoute
  '/reconciliation': typeof AppReconciliationRoute
  '/reports': typeof AppReportsRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
  '/invoices/new': typeof AppInvoicesNewRoute
  '/masters/customers': typeof AppMastersCustomersRoute
  '/masters/products': typeof AppMastersProductsRoute
  '/returns/gstr-1': typeof AppReturnsGstr1Route
  '/returns/gstr-3b': typeof AppReturnsGstr3bRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/invoices/': typeof AppInvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/business': typeof AppBusinessRoute
  '/einvoice': typeof AppEinvoiceRoute
  '/reconciliation': typeof AppReconciliationRoute
  '/reports': typeof AppReportsRoute
  '/': typeof AppIndexRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
  '/invoices/new': typeof AppInvoicesNewRoute
  '/masters/customers': typeof AppMastersCustomersRoute
  '/masters/products': typeof AppMastersProductsRoute
  '/returns/gstr-1': typeof AppReturnsGstr1Route
  '/returns/gstr-3b': typeof AppReturnsGstr3bRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/invoices': typeof AppInvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/business': typeof AppBusinessRoute
  '/_app/einvoice': typeof AppEinvoiceRoute
  '/_app/reconciliation': typeof AppReconciliationRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/invoices/$id': typeof AppInvoicesIdRoute
  '/_app/invoices/new': typeof AppInvoicesNewRoute
  '/_app/masters/customers': typeof AppMastersCustomersRoute
  '/_app/masters/products': typeof AppMastersProductsRoute
  '/_app/returns/gstr-1': typeof AppReturnsGstr1Route
  '/_app/returns/gstr-3b': typeof AppReturnsGstr3bRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/invoices/': typeof AppInvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/business'
    | '/einvoice'
    | '/reconciliation'
    | '/reports'
    | '/invoices/$id'
    | '/invoices/new'
    | '/masters/customers'
    | '/masters/products'
    | '/returns/gstr-1'
    | '/returns/gstr-3b'
    | '/api/auth/$'
    | '/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/business'
    | '/einvoice'
    | '/reconciliation'
    | '/reports'
    | '/'
    | '/invoices/$id'
    | '/invoices/new'
    | '/masters/customers'
    | '/masters/products'
    | '/returns/gstr-1'
    | '/returns/gstr-3b'
    | '/api/auth/$'
    | '/invoices'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/business'
    | '/_app/einvoice'
    | '/_app/reconciliation'
    | '/_app/reports'
    | '/_app/'
    | '/_app/invoices/$id'
    | '/_app/invoices/new'
    | '/_app/masters/customers'
    | '/_app/masters/products'
    | '/_app/returns/gstr-1'
    | '/_app/returns/gstr-3b'
    | '/api/auth/$'
    | '/_app/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/business': {
      id: '/_app/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof AppBusinessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/einvoice': {
      id: '/_app/einvoice'
      path: '/einvoice'
      fullPath: '/einvoice'
      preLoaderRoute: typeof AppEinvoiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reconciliation': {
      id: '/_app/reconciliation'
      path: '/reconciliation'
      fullPath: '/reconciliation'
      preLoaderRoute: typeof AppReconciliationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/': {
      id: '/_app/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/$id': {
      id: '/_app/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AppInvoicesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/new': {
      id: '/_app/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AppInvoicesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/masters/customers': {
      id: '/_app/masters/customers'
      path: '/masters/customers'
      fullPath: '/masters/customers'
      preLoaderRoute: typeof AppMastersCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/masters/products': {
      id: '/_app/masters/products'
      path: '/masters/products'
      fullPath: '/masters/products'
      preLoaderRoute: typeof AppMastersProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/returns/gstr-1': {
      id: '/_app/returns/gstr-1'
      path: '/returns/gstr-1'
      fullPath: '/returns/gstr-1'
      preLoaderRoute: typeof AppReturnsGstr1RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/returns/gstr-3b': {
      id: '/_app/returns/gstr-3b'
      path: '/returns/gstr-3b'
      fullPath: '/returns/gstr-3b'
      preLoaderRoute: typeof AppReturnsGstr3bRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppBusinessRoute: typeof AppBusinessRoute
  AppEinvoiceRoute: typeof AppEinvoiceRoute
  AppReconciliationRoute: typeof AppReconciliationRoute
  AppReportsRoute: typeof AppReportsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppInvoicesIdRoute: typeof AppInvoicesIdRoute
  AppInvoicesNewRoute: typeof AppInvoicesNewRoute
  AppMastersCustomersRoute: typeof AppMastersCustomersRoute
  AppMastersProductsRoute: typeof AppMastersProductsRoute
  AppReturnsGstr1Route: typeof AppReturnsGstr1Route
  AppReturnsGstr3bRoute: typeof AppReturnsGstr3bRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBusinessRoute: AppBusinessRoute,
  AppEinvoiceRoute: AppEinvoiceRoute,
  AppReconciliationRoute: AppReconciliationRoute,
  AppReportsRoute: AppReportsRoute,
  AppIndexRoute: AppIndexRoute,
  AppInvoicesIdRoute: AppInvoicesIdRoute,
  AppInvoicesNewRoute: AppInvoicesNewRoute,
  AppMastersCustomersRoute: AppMastersCustomersRoute,
  AppMastersProductsRoute: AppMastersProductsRoute,
  AppReturnsGstr1Route: AppReturnsGstr1Route,
  AppReturnsGstr3bRoute: AppReturnsGstr3bRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
